# Copyright 2022 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# The definition of the HALv3 characteristics can be found in
# system/media/camera/include/system/camera_metadata_tags.h

# Front camera.
camera0.lens_facing=0
camera0.sensor_orientation=0
# lenovo300e
camera0.module0.usb_vid_pid=30c9:001e
camera0.module0.lens_info_available_apertures=2.0
camera0.module0.lens_info_available_focal_lengths=1.31
# lenovo300e
camera0.module1.usb_vid_pid=5986:1163
camera0.module1.lens_info_available_apertures=2.0
camera0.module1.lens_info_available_focal_lengths=1.31
# lg whalebook2
camera0.module2.usb_vid_pid=04f2:b67a
camera0.module2.lens_info_available_apertures=2.0
camera0.module2.lens_info_available_focal_lengths=1.31
# lg whalebook2 CAMERA 1M 720P MICX2/CKFNH1421005110LH
camera0.module3.usb_vid_pid=04f2:b811
camera0.module3.lens_info_available_apertures=2.0
camera0.module3.lens_info_available_focal_lengths=1.31
# lg whalebook2 CAMERA 1M 720P MICX2/AZWAVE/AM-3SF54B9-A
camera0.module4.usb_vid_pid=13d3:54b9
camera0.module4.lens_info_available_apertures=2.0
camera0.module4.lens_info_available_focal_lengths=1.31
# poin2
camera0.module5.usb_vid_pid=0bda:5830
camera0.module5.lens_info_available_apertures=2.0
camera0.module5.lens_info_available_focal_lengths=1.31
# ASUS BR1100FKA
camera0.module6.usb_vid_pid=13d3:56ea
camera0.module6.lens_info_available_apertures=2.0
camera0.module6.lens_info_available_focal_lengths=1.31
# lg whalebook4
camera0.module7.usb_vid_pid=13d3:52c1
camera0.module7.lens_info_available_apertures=2.0
camera0.module7.lens_info_available_focal_lengths=1.31

# Back camera.
camera1.lens_facing=1
camera1.sensor_orientation=0
# lenovo300e
camera1.module0.usb_vid_pid=04ca:707a
camera1.module0.lens_info_available_apertures=2.0
camera1.module0.lens_info_available_focal_lengths=1.31
# lenovo300e
camera1.module1.usb_vid_pid=04f2:b688
camera1.module1.lens_info_available_apertures=2.0
camera1.module1.lens_info_available_focal_lengths=1.31
# lg whalebook2
camera1.module2.usb_vid_pid=04f2:b786
camera1.module2.lens_info_available_apertures=2.0
camera1.module2.lens_info_available_focal_lengths=1.31
# lg whalebook3
camera1.module3.usb_vid_pid=04f2:b7f6
camera1.module3.lens_info_available_apertures=2.0
camera1.module3.lens_info_available_focal_lengths=1.31
# lg whalebook3 CAMERA MODULE 5M LED/AZWAVE/AM-3BA5533-A
camera1.module4.usb_vid_pid=13d3:5533
camera1.module4.lens_info_available_apertures=2.0
camera1.module4.lens_info_available_focal_lengths=1.31
# poin2
camera1.module5.usb_vid_pid=1bcf:284d
camera1.module5.lens_info_available_apertures=2.0
camera1.module5.lens_info_available_focal_lengths=1.31
# poin2
camera1.module6.usb_vid_pid=16cf:28c4
camera1.module6.lens_info_available_apertures=2.0
camera1.module6.lens_info_available_focal_lengths=1.31
