# Copyright 2024 NAVER Authors. All rights reserved.
# tmpfiles.d configuration for Waydroid
# Only creates /run directories (tmpfs, no SELinux label required).
# /var/lib/waydroid and /var/lib/lxc are created at runtime by the
# waydroid-container Upstart job to avoid SELinux context failures
# during early-boot tmpfiles-setup.

# Type  Path                              Mode  User  Group  Age
d=      /run/waydroid                     0755  root  root   -
d=      /run/waydroid-lxc                 0755  root  root   -
