# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Clean up any leftover lock files https://github.com/fwupd/fwupd/issues/7188
r /run/lock/power_override/fwupd.lock
