#!/bin/bash
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -eu -o pipefail

# We'll eventually want to pass in the build orchestrator (Bazel or Portage) and
# choose the appropriate value based on the parent orchestrator. But for now we
# don't have enough RBE workers to support building on the "bazel" worker
# pool so we'll hard-code this to "portage" for now.
build_orchestrator="portage"

# Use the same container image as the one used by chrome. It just works and using the same image
# is good in terms of cache efficiency. The container image was built with this Dockerfile:
# https://chromium.googlesource.com/infra/infra/+/main/rbe/images/siso-chromium/linux/Dockerfile
DOCKER_IMAGE=docker://gcr.io/chops-public-images-prod/rbe/siso-chromium/linux@sha256:26de99218a1a8b527d4840490bcbf1690ee0b55c84316300b60776e6b3a03fe1
WORKER_LABELS=label:orchestrator=${build_orchestrator},label:package_accelerator=reclient,label:core_count=2

# Allow passing rewrapper args if they are at the beginning.
# A `--` is required in this case to separate the rewrapper args from the
# real command.
WRAPPER_ARGS=()
if [[ "$#" -ge 1 && "$1" =~ ^- ]]; then
  while [[ "$#" -ge 1 ]]; do
    if [[ "$1" == "--" ]]; then
      shift
      break
    else
      WRAPPER_ARGS+=("$1")
      shift
    fi
  done
fi

if [[ "$#" -gt 1 && "$1" =~ -gcc ]]; then
  LABELS="type=compile,compiler=clang,lang=cpp"
else
  LABELS="type=tool"
fi

# Make all absolute paths relative so we don't need to use the dockerChrootPath
# attribute. Using a chroot causes the sub-tool wrappers to fail since
# there isn't a version of `sh` available unless we provide one.
if [[ -v WORKDIR ]]; then
  rel="$(realpath --relative-to . "${WORKDIR}")"
  set -- "${@//"${WORKDIR}"/"${rel}"}"

  if [[ -v SYSROOT ]]; then
    # sysroot symlink is created by the ebuild.
    set -- "${@//"${SYSROOT}"/"${rel}/sysroot"}"
  fi
fi

ARGS=(
  "${CROS_REMOTEEXEC_REWRAPPER_PATH?}"
  -server_address="${RBE_server_address?}"
  -log_dir="${RBE_log_dir?}"
  -platform="container-image=${DOCKER_IMAGE},dockerRuntime=runsc,${WORKER_LABELS}"
  -exec_strategy="remote_local_fallback"
  -dial_timeout="10m"
  -exec_timeout="2m"
  -reclient_timeout="10m"
  -exec_root="${WORKDIR:-/}"
  -labels="${LABELS}"
  # -alsologtostderr
  "${WRAPPER_ARGS[@]}"

)

# Hack because reclient doesn't create the CWD unless it contains a file.
# b/392166811.
if [[ -e ".empty" ]]; then
  ARGS+=(
    -inputs "$(realpath --relative-to "${WORKDIR:-/}" .empty)"
  )
fi

ARGS+=(-- "$@")

# Disable the portage sandbox so we don't pollute the RBE environment with
# non-hermetic variables.
export SANDBOX_ON=0

: "${CROS_REMOTEEXEC_DEBUG:=}"
if [[ "${CROS_REMOTEEXEC_DEBUG}" == 1 || "${CROS_REMOTEEXEC_DEBUG}" == "true" ]]; then
  set -x
fi

# Use env to improve cache hits.
exec env -i "${ARGS[@]}"
